---
- name: Install qemu-guest-agent package
  hosts: "{{ hosts }}"
  become: true
  become_method: sudo
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
