---
- name: MySQL Database Backup and Restore
  hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: Backup MySQL Database
      mysql_db:
        name: "{{ database_name }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        state: dump
        target: "{{ dump_root_dir }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}.sql"
      register: backup_result

    - name: Restore MySQL Database
      mysql_db:
        name: "{{ database_name }}"
        state: import
        target: "{{ dump_file_path }}"
      when: restore_database | default(0)

  vars:
    restore_database: "{{ restore_status }}"  # Set this to true if you want to restore the database
